# 应用名称
spring:
  application:
    name: tcc-order-account
  datasource:
    # 数据源配置
    name: tccAccount
    url: jdbc:mysql://localhost:3306/tcc-account?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: tcc-order-user
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#druid连接池配置
druid:
  #配置监控统计拦截的filters，stat:监控统计; slf4j：日志记录; wall：防御sql注入
  filter:
    slf4j:
      enabled: true
    stat:
      enabled: true
      db-type: mysql
    wall:
      enabled: true
      db-type: mysql
  #初始化连接池的连接数量 大小，最小，最大
  initial-size: 5
  min-idle: 5
  max-active: 20
  #配置获取连接等待超时的时间
  max-wait: 60000
  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  time-between-eviction-runs-millis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  min-evictable-idle-time-millis: 30000
  validation-query: SELECT 1 FROM DUAL
  test-while-idle: true
  test-on-borrow: true
  test-on-return: false
  # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭
  pool-prepared-statements: false
  max-pool-prepared-statement-per-connection-size: 20

# eureka服务端口
server:
  port: 8002

# eureka配置信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
