# 应用名称
spring:
  application:
    name: tcc-order-order
  datasource:
    # 数据源配置
    name: tccOrder
    url: jdbc:mysql://localhost:3306/tcc-order?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: tcc-order-user
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid连接池配置
    #配置监控统计拦截的filters，stat:监控统计; slf4j：日志记录; wall：防御sql注入
    filter:
      slf4j:
        enabled: true
      stat:
        enabled: true
        db-type: mysql
      wall:
        enabled: true
        db-type: mysql
    #初始化连接池的连接数量 大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    #配置获取连接等待超时的时间
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 30000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20

# eureka服务端口
server:
  port: 8004

# eureka配置信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

# seata配置
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  registry:
    type: eureka
    eureka:
      service-url: http://localhost:8000/eureka
      application: tcc-order-seata-server
      weight: 1
  config:
    type: file
  client:
    log:
      exception-rate: 100
    rm:
      async-commit-buffer-limit: 10000
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
  service:
    vgroup-mapping:
      order_tx_group: tcc-order-seata-server
  tx-service-group: order_tx_group

# feign配置
feign:
  httpclient:
    connection-timeout: 2000

