# 应用名称
spring:
  application:
    name: tcc-order-eureka-server

# eureka服务端口
server:
  port: 8000

# eureka配置信息
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost